#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'net/http'
require 'time'
require 'fileutils'

MAX_RUBY_FILES = 500

dest = ARGV[0] or abort('usage: script/fetch-fresh-corpus DEST_DIR [LIMIT] [HOURS]')
limit = Integer(ARGV[1] || 100)
hours = Integer(ARGV[2] || 24)

now = Time.now.utc
to = Time.utc(now.year, now.month, now.day)
from = to - (hours * 3600)
versions = []
(1..).each do |page|
  uri = URI('https://rubygems.org/api/v1/timeframe_versions.json')
  uri.query = URI.encode_www_form(from: from.iso8601, to: to.iso8601, page: page)
  batch = JSON.parse(Net::HTTP.get(uri))
  break if batch.empty?

  versions.concat(batch)
end

latest = versions.select { |v| v['platform'] == 'ruby' }
                 .reverse
                 .uniq { |v| v['name'] }
                 .first(limit)

FileUtils.mkdir_p(dest)
queue = Queue.new
latest.each { |v| queue << v }
queue.close

workers = Array.new(8) do
  Thread.new do
    while (v = queue.pop)
      gem = "#{v['name']}-#{v['number']}"
      ok = system('gem', 'fetch', v['name'], '-v', v['number'], chdir: dest, out: File::NULL, err: File::NULL) &&
           system('gem', 'unpack', "#{gem}.gem", chdir: dest, out: File::NULL, err: File::NULL)
      FileUtils.rm_f(File.join(dest, "#{gem}.gem"))
      dir = File.join(dest, gem)
      if ok && Dir.glob(File.join(dir, '**', '*.rb')).size > MAX_RUBY_FILES
        FileUtils.rm_rf(dir)
        ok = false
      end
      ok ? puts("ok #{gem}") : warn("skip #{gem}")
    end
  end
end
workers.each(&:join)
